spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/tourist_pathfinder_2024?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: ${password}
  sql:
    init:
      mode: never
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
  mvc:
    hidden-method:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
    resources:
      static-locations:file:./src/main/resources/static/
    cache-period: 0

app:
  default:
    password: pako
server:
  port: 1038
logging:
  level:
    org.springframework.security: TRACE


